panel: fix build - move maybe_read_id above prepare, drop dead label
  .../panel-tianma-tl060fvxs07.c:327:9: error: implicit declaration of
      function 'tl060fvxs07_maybe_read_id' [-Werror=implicit-function-declaration]
  .../panel-tianma-tl060fvxs07.c:345:13: error: static declaration of
      'tl060fvxs07_maybe_read_id' follows non-static declaration
  .../panel-tianma-tl060fvxs07.c:331:1: warning: label 'disable_iovcc'
      defined but not used

maybe_read_id was defined after tl060fvxs07_prepare(), and the disable_iovcc
label became unreachable when the prepare failure path started returning 0
(the panel may still come up, so we no longer tear the supplies down there).